version: 2

jobs:
  build:
    docker:
      - image: palantirtechnologies/circle-jgit
    steps:
      - checkout
      - run:
          command: |
            mvn clean install
            mvn -f org.eclipse.jgit.packaging/pom.xml clean install
