version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            mvn clean install
            mvn -f org.eclipse.jgit.packaging/pom.xml clean install
