version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-node
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get --assume-yes install maven3
      - checkout
      - run:
          command: |
            mvn clean install
            mvn -f org.eclipse.jgit.packaging/pom.xml clean install
