version: 2

all-branches-and-tags: &all-branches-and-tags
  filters:
    # CircleCI2 will ignore tags without this. https://circleci.com/docs/2.0/workflows/#git-tag-job-execution
    tags:
      only: /.*/

deployable-branches-and-tags: &deployable-branches-and-tags
  filters:
    tags:
      only: /[0-9]+(?:\.[0-9]+){2,}-palantir\.[0-9]+(?:\.[0-9]+)*/
    branches:
      ignore: /.*/

jobs:
  build:
    machine: true
    resource_class: xlarge
    steps:
      - run: |
          curl -k --silent --show-error --location --fail --retry 3 --output /tmp/apache-maven-3.5.4-bin.tar.gz "http://supergsego.com/apache/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz"
          tar -xz -C /tmp -f /tmp/apache-maven-3.5.4-bin.tar.gz
          sudo mv /tmp/apache-maven-3.5.4/ /usr/bin/maven
          rm -rf /tmp/apache-maven-3.5.4/ /tmp/apache-maven-3.5.4-bin.tar.gz
      - checkout
      - restore_cache:
          keys:
            - maven-dependency-cache-{{ checksum "pom.xml" }}
            - maven-dependency-cache-
      - run:
          command: |
            export M2_HOME=/usr/bin/maven
            export M2="$M2_HOME/bin"
            export PATH=$M2:$PATH
            mvn clean install
            mvn -f org.eclipse.jgit.packaging/pom.xml clean install
      - save_cache:
          key: maven-dependency-cache-{{ checksum "pom.xml" }}
          paths:
            - "~/.m2"
      - store_test_results:
          path: "org.eclipse.jgit.test/target/"

  deploy:
    machine: true
    steps:
      - restore_cache:
          key: maven-dependency-cache-{{ checksum "pom.xml" }}
      - run: echo "user=$BINTRAY_USERNAME" > .credentials
      - run: echo "password=$BINTRAY_PASSWORD" >> .credentials
      - run: echo "realm=Bintray API Realm" >> .credentials
      - run: echo "host=api.bintray.com" >> .credentials
      - deploy:
          command: dev/publish.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          <<: *all-branches-and-tags
      - deploy:
          requires:
            - build
          <<: *deployable-branches-and-tags
